root = "."
tmp_dir = "tmp"
[build]
  pre_cmd = ["tailwindcss -i ./public/css/input.css -o ./public/css/tailwind.css --minify"]
  cmd = "go build -o ./tmp/main.exe ."
  bin = "./tmp/main"
  delay = 1000 # ms
  exclude_dir = ["assets", "tmp", "vendor", "node_modules"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]